import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:8080/login', { waitUntil: 'networkidle' });
await page.fill('input[type="email"]', 'd@fleet.com');
await page.fill('input[type="password"]', 'pass123');
await page.click('button[type="submit"]');
await page.waitForURL('**/loadboard', { timeout: 8000 });
await page.waitForTimeout(1500);
await page.screenshot({ path: 'control-tower.png', fullPage: true });
console.log('saved control-tower.png');
await page.goto('http://localhost:8080/login', { waitUntil: 'domcontentloaded' });
await browser.close();
